name: Build and Test C Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build
      run: gcc -o demo main.c

    - name: Run Tests
      run: |
        echo -e "1\n2\n3\n4\n5\n6\n7\n8\n9\n10" | ./demo
