name: Build and Test C Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build
      run: gcc -o demo main.c

    - name: Run Tests
      run: |
        ./demo <<EOF
1
2
3
4
5
6
7
8
9
10
EOF

      
